[package]
name = "GraphQLRust"
version = "0.1.0"
authors = ["Salomon-Novachrono <[Salomon.Novachrono@gmail.com]>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
